name: barc-blanket-env

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy
  - pandas
  - matplotlib
  - openmc
  - dash
  - plotly
  - pip
  - scipy ==1.11.4
  - pip:
    - openmc_regular_mesh_plotter