metric: tbr
parameters:
  run_mode:
    distribution: categorical
    values:
    - 'eigenvalue'
  batches:
    distribution: categorical
    values:
    - 40
  inactive_batches:
    distribution: categorical
    values:
    - 5
  particles:
    distribution: categorical
    values:
    - 10000
  li6_enrichment:
    distribution: float
    max: 0.6
    min: 0.0
    step: 0.3
    log: false
  fissile_enrichment:
    distribution: float
    max: 0.2
    min: 0.0
    step: 0.05
    log: false
